module.exports = {
  apps: [
    {
      name: 'inkblog-backend',
      script: './main',
      cwd: '/root/inkblog/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env: {
        NODE_ENV: 'production',
        NOTIFICATION_SERVICE_URL: 'http://127.0.0.1:13160',
        NOTIFICATION_SERVICE_TOKEN: 'inkblog-notification-dev-token',
      },
      error_file: '../logs/backend-error.log',
      out_file: '../logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      kill_timeout: 3000,
      restart_delay: 4000,
      min_uptime: '10s',
      max_restarts: 10,
    },
    {
      name: 'inkblog-notification',
      script: './notification',
      cwd: '/root/inkblog/backend',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        NOTIFICATION_PORT: '13160',
        NOTIFICATION_SERVICE_URL: 'http://127.0.0.1:13160',
        NOTIFICATION_SERVICE_TOKEN: 'inkblog-notification-dev-token',
      },
      error_file: '../logs/notification-error.log',
      out_file: '../logs/notification-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
      kill_timeout: 3000,
      restart_delay: 4000,
      min_uptime: '10s',
      max_restarts: 10,
    },
  ],
};

